---
title: "GeoTcgaData"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GeoTcgaData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```
--------

## Authors
Erqiang Hu

Department of Bioinformatics, School of Basic Medical Sciences, 
Southern Medical University.


```{r setup}
library(multiEnrichment)
data(multiGene)
data(TERM2GENE)
data(network)
```

Multiple omics forms for ORA algorithm.
```{r message=FALSE, warning=FALSE}
# output: enrichResult
enricher_result <- multiEnrichment(multiGene = multiGene, method = "enricher", 
                                   TERM2GENE = TERM2GENE) 
class(enricher_result)
head(enricher_result)
# output: compareClusterResult
enricher_result2 <- multiEnrichment(multiGene = multiGene, method = "enricher", 
                                    TERM2GENE = TERM2GENE, 
                                    output = "compareClusterResult") 
class(enricher_result2)
head(enricher_result2)

# combinelevel = "gene"
enricher_result3 <- multiEnrichment(multiGene = multiGene, method = "enricher", 
                                   TERM2GENE = TERM2GENE, combineLevel = "gene") 
class(enricher_result3)
head(enricher_result3)
```


Multiple omics forms for GSEA algorithm.
```{r message=FALSE, warning=FALSE}
# output: multiGseaResult
GSEA_result <- multiEnrichment(multiGene = multiGene, method = "GSEA", 
                               TERM2GENE = TERM2GENE)  
class(GSEA_result)
head(GSEA_result)
# output: compareClusterResult
GSEA_result2 <- multiEnrichment(multiGene = multiGene, method = "GSEA", 
                                TERM2GENE = TERM2GENE, 
                                output = "compareClusterResult")
class(GSEA_result2)
head(GSEA_result2)
# combinelevel = "gene"
GSEA_result3 <- multiEnrichment(multiGene = multiGene, method = "GSEA", 
                               TERM2GENE = TERM2GENE, combineLevel = "gene")  
class(GSEA_result3)
head(GSEA_result3)
```

mitch algorithm
```{r message=FALSE, warning=FALSE}
# output: enrichResult
mitch_result <- multiEnrichment(multiGene = multiGene, method = "mitch", 
                                TERM2GENE = TERM2GENE)
class(mitch_result)
head(mitch_result)
```

ActivePathways algorithm
```{r message=FALSE, warning=FALSE}
# output: enrichResult
ActivePathways_result <- multiEnrichment(multiGene = multiGene, 
                                         method = "ActivePathways", 
                                         TERM2GENE = TERM2GENE)
class(ActivePathways_result)
head(ActivePathways_result)
```

multiNetEnrich algorithm
```{r eval=TRUE, message=FALSE, warning=FALSE}
# output: enrichResult
multiNetEnrich_result <- multiEnrichment(multiGene = multiGene, 
                                         method = "multiNetEnrich", 
                                         TERM2GENE = TERM2GENE, 
                                         network = network) 
class(multiNetEnrich_result)
head(multiNetEnrich_result)
# output: compareClusterResult
multiNetEnrich_result2 <- multiEnrichment(multiGene = multiGene, 
                                          method = "multiNetEnrich", 
                                          TERM2GENE = TERM2GENE, 
                                          network = network, 
                                          output = "compareClusterResult") 
class(multiNetEnrich_result2)
head(multiNetEnrich_result2)

# use a list of network
networkList <- list(RNA = network, methy = network)
# output: enrichResult
multiNetEnrich_result3 <- multiEnrichment(multiGene = multiGene, 
                                         method = "multiNetEnrich", 
                                         TERM2GENE = TERM2GENE, 
                                         network = networkList) 
class(multiNetEnrich_result3)
head(multiNetEnrich_result3)
# output: compareClusterResult
multiNetEnrich_result4 <- multiEnrichment(multiGene = multiGene, 
                                          method = "multiNetEnrich", 
                                          TERM2GENE = TERM2GENE, 
                                          network = networkList, 
                                          output = "compareClusterResult") 
class(multiNetEnrich_result4)
head(multiNetEnrich_result4)
# combinelevel = "gene"
multiNetEnrich_result5 <- multiEnrichment(multiGene = multiGene, 
                                         method = "multiNetEnrich", 
                                         TERM2GENE = TERM2GENE, 
                                         network = network,
                                         combineLevel = "gene") 
class(multiNetEnrich_result5)
head(multiNetEnrich_result5)
```


```{r}
sessionInfo()
```
